### ISSUE TITLE
Folder watchers

### ISSUE THREAD

**Issue by pink1stools** [pink1stools/PS3gbs#3]
We need folder watchers for the 3 game file types to refresh the list if a new game is added. For the pkgs and iso's this is simple but for the game folders we will need to check for new folders and then check for I'm not sure what files yet.

**Comment by DeViL303** [comment]
I suppose checking for a param.sfo? Also i suppose the pkg folder should check for added folders too, in case a extracted pkg is added. This could also check for param.sfo. in the case of extracted pkgs a "build pkg" button would be needed instead of "extract pkg"

**Comment by xXxTheDarkprogramerxXx** [comment]
private void watch()
{
//initilaize filesystemwatcher 
  FileSystemWatcher watcher = new FileSystemWatcher();
  watcher.Path = path;//iso path //pkg path //sfo path in working 
  watcher.NotifyFilter = NotifyFilters.LastWrite; //look for last time change
  watcher.Filter = "*.*"; //filter extentions 
  watcher.Changed += new FileSystemEventHandler(OnChanged); //fire up the reload method 
  watcher.EnableRaisingEvents = true; //Obviously xD 
}

**Comment by xXxTheDarkprogramerxXx** [comment]
Folder watcher committed

**Comment by pink1stools** [comment]
As I go on the scanning I'm trying to get the watchers added too.
