### ISSUE TITLE
Update buttons 

### ISSUE THREAD

**Issue by pink1stools** [pink1stools/PS3gbs#4]
We need update buttons for the selected game and a search button in the update tap.

**Comment by xXxTheDarkprogramerxXx** [comment]
[icons.zip](https://github.com/pink1stools/PS3gbs/files/2391297/icons.zip)

**Comment by xXxTheDarkprogramerxXx** [comment]
Added icons from Free icon finder imho svg's are better than png they keep sizing way better

**Comment by pink1stools** [comment]
I need to add a browse button to look for files for updates. The updates button in the pkg is now working and added badges to show the number of updates to the icons.
